### ISSUE TITLE
Continually asked to update to the same version

### ISSUE THREAD

**Issue by redsward** [RoboMagus/OctoPrint-LightControls#1]
Each time I open octoprint light controls asks to update .

**Comment by RoboMagus** [comment]
Thanks for letting me know. 
I'll look into it somewhere this week when make some other changes as well.

**Comment by RoboMagus** [comment]
I've just pushed the latest changes which included the proper version increment.
There should no longer be a recurring prompt to update to v0.1.1.

Should the problem persist, please re-open this issue.

**Comment by redsward** [comment]
Thanks Appreciated !

John Bayley | Head of Production

[x]

Level 5, 10 Hickson Road, The Rocks, NSW 2000, Australia
Ph: +61 2 82486527  M: +61 417486583

***@***.******@***.***<https://twitter.com/sydney_festival> ***@***.*** <https://instagram.com/sydney_festival/>   ***@***.*** <https://www.youtube.com/user/SydneyFestival>  ***@***.*** <http://www.sydneyfestival.org.au/info/subscribe-to-enews>

I would like to acknowledge the Traditional Owners of the land on which Sydney Festival takes place, and pay respect to the 29 clans
of the Eora Nation. I would also like to acknowledge that this land falls within the boundaries of the Metropolitan Local Aboriginal Land
Council. I would like to pay respect to Elders both past and present, and all Aboriginal peoples whichever nation they come from.

This email may contain confidential information which is for the use of intended recipients only.
If you receive this email in error please delete it and advise the sender. Sydney Festival
accepts no responsibility for content that is not related to our official business, nor the
secure transmission or privacy of messages, or possible viruses.
