### ISSUE TITLE
[BUG]: Combo box control does not function

### ISSUE THREAD

**Issue by brooksware2000** [RoboMagus/OctoPrint-LightControls#4]
**Describe the bug**
I assume the combo box control should allow one to edit the PWM range (0-100%).  Entering a value and/or using the up-down buttons in the combo box does not function.

**Expected behavior**
Recommend adding functionality to allow the combo box or the slider to affect the PWM range.  Also, I recommend values entered in the combo box be synced back to the slider control.

**Debug logs**

**Screenshots**

**Additional context**

**Comment by RoboMagus** [comment]
Good catch! 

Thanks for the report. I've just tested it myself and it's a clear issue. 
I'll see if I can release a fix for this in the next couple of days.

**Comment by RoboMagus** [comment]
This was easier than expected.
Please update to version **0.4.0** which includes a fix for this issue.
