### ISSUE TITLE
[BUG]:  Won't update to version 0.4.0

### ISSUE THREAD

**Issue by Damien0505** [RoboMagus/OctoPrint-LightControls#5]
**Describe the bug**
Octoprint won't update plugin to 0.4.0

**Expected behavior**
Should update to 0.4.0

**Debug logs**
N/A

**Screenshots**
N/A

**Additional context**
Plugin will not update to to version not being updated in setup.py
Downloading 0.4.0 release zip and editing version in setup.py to 0.4.0 allows plugin to be updated by manual upload.

**Comment by RoboMagus** [comment]
Thanks for the report!
I forgot to bump the internal version. Just pushed 0.4.1, which should fix that.
